root: true

parser: babel-eslint

extends:
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:jest/recommended
  - standard

plugins:
  - react
  - jsx-a11y
  - jest
  - standard

settings:
  react:
    pragma: wp

env:
  browser: false
  es6: true
  node: true
  mocha: true
  jest/globals: true

globals:
  wp: true
  wpApiSettings: true
  window: true
  document: true

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  max-len: [error, { code: 120 }]
  quotes: [error, single]
  space-before-function-paren: 0
